# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "pn-mtk"
BBFILE_PATTERN_pn-mtk = "^${LAYERDIR}/"
BBFILE_PRIORITY_pn-mtk = "9"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_pn-mtk = "1"

LAYERDEPENDS_pn-mtk = " \
	core \
	mediatek-bsp \
	mediatek-tsn \
	mediatek-bluedroid \
	mediatek-demo \
	multimedia-layer \
	openembedded-layer \
	networking-layer \
	meta-python \
"

LAYERSERIES_COMPAT_pn-mtk = "scarthgap"
